### ISSUE TITLE
防抖代码编写出错

### ISSUE THREAD

**Issue by yankfy** [i-want-offer/FE-Essay#14]
## 文章编写错误

```js
function throttle(fn: () => void, delay: number) {
  let flag = true
  return function() {
    if(!flag) return
    flag = false
    setTimeout(function() {
      fn()
      flag = true
    }, delay)
  }
}
```
防抖代码好像写错了~

## 应该正确的结果

```js
function throttle(fn: () => void, delay: number) {
  let flag = null
  return function() {
    if(!flag){ // flag 上面错误代码初始化为true的话一直就return了~
    setTimeout(()=>{ // 箭头函数，否则this指向变了
      fn()
      flag = null
    }, delay)
  }
}
```

**Comment by LaamGinghong** [comment]
> ## 文章编写错误
> ```js
> function throttle(fn: () => void, delay: number) {
>   let flag = true
>   return function() {
>     if(!flag) return
>     flag = false
>     setTimeout(function() {
>       fn()
>       flag = true
>     }, delay)
>   }
> }
> ```
> 
> 防抖代码好像写错了~
> 
> ## 应该正确的结果
> ```js
> function throttle(fn: () => void, delay: number) {
>   let flag = null
>   return function() {
>     if(!flag){ // flag 上面错误代码初始化为true的话一直就return了~
>     setTimeout(()=>{ // 箭头函数，否则this指向变了
>       fn()
>       flag = null
>     }, delay)
>   }
> }
> ```

我觉得我写的应该没有问题，我们理一下。你现在看到的是一个节流函数，我上面的这个节流函数，一开始执行这个节流函数时，因为初始 flag 为 true，此时并不会被条件语句给拦截，之后 flag 被设置为 false，并且执行了 setTimeout 函数，延迟函数里面包含了传进来的 fn 以及将 flag 重新设置为 true。
之后再次执行这个函数的时候，因为 flag 被设置为了 false，所以会被条件语句拦截，直至延迟函数被执行，flag 重新被设置为 true。
从执行逻辑上说，上述应该并不会包含你所说的问题。至于 setTimeout 是否需要修改为箭头函数，其实我个人为没有必要，因为里面并没有包含 this。
但是上面包含一个问题，在于传进来的 fn 的 this 问题。
具体你可以看 [手写节流](https://github.com/i-want-offer/FE-Essay/blob/master/docs/%E6%89%8B%E5%86%99%E4%BB%A3%E7%A0%81/dt/throttle.js) 。你能看懂这个，应该可以理清楚。

**Comment by LaamGinghong** [comment]
@yankfy

**Comment by yankfy** [comment]
===我脑子瓦特了===Sorry
