### ISSUE TITLE
await 执行顺序问题

### ISSUE THREAD

**Issue by Jancat** [i-want-offer/FE-Essay#4]
在 https://github.com/i-want-offer/FE-Essay/blob/master/JS/%E4%BA%8B%E4%BB%B6%E5%BE%AA%E7%8E%AF.md 中，

```js
async function async1() {
    await async2()
}

async1()

// 第一种
async function async2() {
  console.log('async2 end')
}

// 第二种
async function async2() {
  console.log('async2 end')
  return Promise.resolve().then(() => {
    console.log('async2 end1')
  })
}
```

第一种和第二种 async2() 异步函数的区别是返回值不同，第一种是返回默认包装的 promise（立即把后面的代码推入微任务队列），第二种是返回新的 promise（本轮循环末尾把后面的代码推入微任务队列），应该是两种 promise 的区别影响了 await 后面的代码的执行时机。

返回新的 promise 时延迟了 await 后面代码的执行时间（具体原理未知，请指教）

**Comment by LaamGinghong** [comment]
> 在 https://github.com/i-want-offer/FE-Essay/blob/master/JS/%E4%BA%8B%E4%BB%B6%E5%BE%AA%E7%8E%AF.md 中，
> 
> ```js
> async function async1() {
>     await async2()
> }
> 
> async1()
> 
> // 第一种
> async function async2() {
>   console.log('async2 end')
> }
> 
> // 第二种
> async function async2() {
>   console.log('async2 end')
>   return Promise.resolve().then(() => {
>     console.log('async2 end1')
>   })
> }
> ```
> 
> 第一种和第二种 async2() 异步函数的区别是返回值不同，第一种是返回默认包装的 promise（立即把后面的代码推入微任务队列），第二种是返回新的 promise（本轮循环末尾把后面的代码推入微任务队列），应该是两种 promise 的区别影响了 await 后面的代码的执行时机。
> 
> 返回新的 promise 时延迟了 await 后面代码的执行时间（具体原理未知，请指教）

可以看下这篇 [文章](https://www.zhihu.com/question/268007969/answer/556250835)。

也可以自己用 babel 解析一下代码，看一下打包出来之后对应会变成什么样子。

不过我其实没有仔细钻研这里面的原理，面试的时候反正记住这里面的差异就行了。
