### ISSUE TITLE
看到一处笔误：constructor拼写错误

### ISSUE THREAD

**Issue by JuneBlueberry** [i-want-offer/FE-Essay#5]
[https://github.com/i-want-offer/FE-Essay/blob/master/JS/%E5%85%A8%E9%9D%A2%E5%88%86%E6%9E%90toString%E5%92%8CvalueOf.md](url)
代码实例里面的constructor拼写错误

**Comment by LaamGinghong** [comment]
url 被转码了，你重新给一个正确的url吧
