### ISSUE TITLE
宏任务微任务的题错了

### ISSUE THREAD

**Issue by hejialianghe** [i-want-offer/FE-Essay#6]
script start
VM183:9 async2 end
VM183:18 Promise
VM183:5 async1 end
VM183:21 promise1
VM183:23 promise2
Promise {<fulfilled>: undefined}
VM183:14 setTimeout

**Comment by LaamGinghong** [comment]
> script start
> VM183:9 async2 end
> VM183:18 Promise
> VM183:5 async1 end
> VM183:21 promise1
> VM183:23 promise2
> Promise {: undefined}
> VM183:14 setTimeout

你可以去到具体的文件发issue，你这样我不知道是哪个地方错了
